/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package com.badlogicgames.quack.parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int DEF = 12;
  /** RegularExpression Id. */
  int VAL = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 15;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 16;
  /** RegularExpression Id. */
  int HEX_LITERAL = 17;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 18;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 20;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 21;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 22;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 23;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 24;
  /** RegularExpression Id. */
  int STRING_LITERAL = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int PART_LETTER = 28;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int LBRACE = 31;
  /** RegularExpression Id. */
  int RBRACE = 32;
  /** RegularExpression Id. */
  int LBRACKET = 33;
  /** RegularExpression Id. */
  int RBRACKET = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int DOT = 37;
  /** RegularExpression Id. */
  int AT = 38;
  /** RegularExpression Id. */
  int ASSIGN = 39;
  /** RegularExpression Id. */
  int LT = 40;
  /** RegularExpression Id. */
  int BANG = 41;
  /** RegularExpression Id. */
  int TILDE = 42;
  /** RegularExpression Id. */
  int HOOK = 43;
  /** RegularExpression Id. */
  int COLON = 44;
  /** RegularExpression Id. */
  int EQ = 45;
  /** RegularExpression Id. */
  int LE = 46;
  /** RegularExpression Id. */
  int GE = 47;
  /** RegularExpression Id. */
  int NE = 48;
  /** RegularExpression Id. */
  int SC_OR = 49;
  /** RegularExpression Id. */
  int SC_AND = 50;
  /** RegularExpression Id. */
  int INCR = 51;
  /** RegularExpression Id. */
  int DECR = 52;
  /** RegularExpression Id. */
  int PLUS = 53;
  /** RegularExpression Id. */
  int MINUS = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int SLASH = 56;
  /** RegularExpression Id. */
  int BIT_AND = 57;
  /** RegularExpression Id. */
  int BIT_OR = 58;
  /** RegularExpression Id. */
  int XOR = 59;
  /** RegularExpression Id. */
  int REM = 60;
  /** RegularExpression Id. */
  int LSHIFT = 61;
  /** RegularExpression Id. */
  int PLUSASSIGN = 62;
  /** RegularExpression Id. */
  int MINUSASSIGN = 63;
  /** RegularExpression Id. */
  int STARASSIGN = 64;
  /** RegularExpression Id. */
  int SLASHASSIGN = 65;
  /** RegularExpression Id. */
  int ANDASSIGN = 66;
  /** RegularExpression Id. */
  int ORASSIGN = 67;
  /** RegularExpression Id. */
  int XORASSIGN = 68;
  /** RegularExpression Id. */
  int REMASSIGN = 69;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 70;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 71;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 72;
  /** RegularExpression Id. */
  int ELLIPSIS = 73;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"def\"",
    "\"val\"",
    "\"var\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
  };

}
