/* Generated By:JavaCC: Do not edit this line. Parser.java */
package com.badlogicgames.quack.parsing;

import com.badlogicgames.quack.ast.*;
import java.util.*;

public class Parser implements ParserConstants {

//===========================================================================
// Parser
//===========================================================================
  final public AstCompilationUnit CompilationUnit() throws ParseException {
        AstModule m;
        AstImport i;
        List<AstImport> imports = new ArrayList<AstImport>();
        AstStruct s;
        List<AstStruct> structs = new ArrayList<AstStruct>();
        AstFunction f;
        List<AstFunction> functions = new ArrayList<AstFunction>();
    m = ModuleDeclaration();
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      i = ImportDeclaration();
                                imports.add(i);
    }
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      if (jj_2_3(2)) {
        s = StructDefinition();
                                      structs.add(s);
      } else if (jj_2_4(2)) {
        f = FunctionDefinition();
                                        functions.add(f);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                AstCompilationUnit cu = new AstCompilationUnit(1, 1);
                cu.setModule(m);
                cu.getImports().addAll(imports);
                cu.getStructs().addAll(structs);
                cu.getFunctions().addAll(functions);
                {if (true) return cu;}
    throw new Error("Missing return statement in function");
  }

  final public AstModule ModuleDeclaration() throws ParseException {
        Token b;
        String m;
    b = jj_consume_token(MODULE);
    m = ModuleName();
                AstModule module = new AstModule(b.beginLine, b.beginColumn);
                module.setName(m);
                {if (true) return module;}
    throw new Error("Missing return statement in function");
  }

  final public AstImport ImportDeclaration() throws ParseException {
        Token b;
        String m;
    b = jj_consume_token(IMPORT);
    m = ModuleName();
                AstImport imp = new AstImport(b.beginLine, b.beginColumn);
                imp.setName(m);
                {if (true) return imp;}
    throw new Error("Missing return statement in function");
  }

  final public String ModuleName() throws ParseException {
        StringBuilder b = new StringBuilder();
        Token t;
    t = jj_consume_token(IDENTIFIER);
                        b.append(t.image);
    label_3:
    while (true) {
      if (jj_2_5(2)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(DOT);
      t = jj_consume_token(IDENTIFIER);
                                    b.append("."); b.append(t.image);
    }
                {if (true) return b.toString();}
    throw new Error("Missing return statement in function");
  }

  final public AstStruct StructDefinition() throws ParseException {
        Token b;
        Token t;
        AstVariableDeclaration f;
        List<AstVariableDeclaration> fields = new ArrayList<AstVariableDeclaration>();
        AstFunction fu;
        List<AstFunction> functions = new ArrayList<AstFunction>();
    b = jj_consume_token(STRUCT);
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_4;
      }
      f = FieldDeclaration();
                                       fields.add(f);
    }
    label_5:
    while (true) {
      if (jj_2_7(2)) {
        ;
      } else {
        break label_5;
      }
      fu = FunctionDefinition();
                                          functions.add(fu);
    }
    jj_consume_token(RBRACE);
                AstStruct struct = new AstStruct(b.beginLine, b.beginColumn);
                struct.setName(t.image);
                struct.getFields().addAll(fields);
                struct.getFunctions().addAll(functions);
                {if (true) return struct;}
    throw new Error("Missing return statement in function");
  }

  final public AstVariableDeclaration FieldDeclaration() throws ParseException {
        Token s=null;
        Token b;
        Token t;
        AstType ty;
    if (jj_2_8(2)) {
      s = jj_consume_token(STATIC);
    } else {
      ;
    }
    if (jj_2_9(2)) {
      b = jj_consume_token(VAL);
    } else if (jj_2_10(2)) {
      b = jj_consume_token(VAR);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    ty = Type();
                AstVariableDeclaration field = new AstVariableDeclaration(b.beginLine, b.beginColumn);
                field.setStatic(s!=null);
                field.setQualifier(b.image.equals("val")?AstVariableDeclaration.Qualifier.Val:AstVariableDeclaration.Qualifier.Var);
                field.setName(t.image);
                field.setType(ty);
                {if (true) return field;}
    throw new Error("Missing return statement in function");
  }

  final public AstFunction FunctionDefinition() throws ParseException {
        Token b;
        Token t;
        List<AstArgument> args;
        AstType rt = null;
        List<AstStatement> body;
    b = jj_consume_token(DEF);
    t = jj_consume_token(IDENTIFIER);
    args = ArgumentList();
    if (jj_2_11(2)) {
      jj_consume_token(COLON);
      rt = Type();
    } else {
      ;
    }
    jj_consume_token(LBRACE);
    body = FunctionBody();
    jj_consume_token(RBRACE);
                AstFunction func = new AstFunction(b.beginLine, b.beginColumn);
                func.setName(t.image);
                func.getArguments().addAll(args);
                func.setReturnType(rt);
                func.getBody().addAll(body);
                {if (true) return func;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstArgument> ArgumentList() throws ParseException {
        List<AstArgument> args = new ArrayList<AstArgument>();
        AstArgument a;
    jj_consume_token(LPAREN);
    if (jj_2_13(2)) {
      a = Argument();
                           args.add(a);
      label_6:
      while (true) {
        if (jj_2_12(2)) {
          ;
        } else {
          break label_6;
        }
        jj_consume_token(COMMA);
        a = Argument();
                                                             args.add(a);
      }
    } else {
      ;
    }
    jj_consume_token(RPAREN);
                {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public AstArgument Argument() throws ParseException {
        Token t;
        AstType ty;
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    ty = Type();
                AstArgument arg = new AstArgument(t.beginLine, t.beginColumn);
                arg.setName(t.image);
                arg.setType(ty);
                {if (true) return arg;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstStatement> FunctionBody() throws ParseException {
        List<AstStatement> stmts;
    stmts = StatementList();
                {if (true) return stmts;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstStatement> StatementList() throws ParseException {
        List<AstStatement> stmts = new ArrayList<AstStatement>();
        AstStatement s;
    label_7:
    while (true) {
      if (jj_2_14(2)) {
        ;
      } else {
        break label_7;
      }
      s = Statement();
                        stmts.add(s);
    }
                {if (true) return stmts;}
    throw new Error("Missing return statement in function");
  }

  final public AstStatement Statement() throws ParseException {
        AstStatement s;
    if (jj_2_15(2)) {
      s = VariableDeclaration();
    } else if (jj_2_16(2)) {
      s = AssignmentOrExpression();
    } else if (jj_2_17(2)) {
      s = Block();
    } else if (jj_2_18(2)) {
      s = IfBlock();
    } else if (jj_2_19(2)) {
      s = WhileBlock();
    } else if (jj_2_20(2)) {
      s = ForBlock();
    } else if (jj_2_21(2)) {
      s = Return();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public AstVariableDeclaration VariableDeclaration() throws ParseException {
        AstVariableDeclaration v;
    v = FieldDeclaration();
                {if (true) return v;}
    throw new Error("Missing return statement in function");
  }

  final public AstBlock Block() throws ParseException {
        Token b;
        List<AstStatement> stmts;
    b = jj_consume_token(LBRACE);
    stmts = StatementList();
    jj_consume_token(RBRACE);
                AstBlock block = new AstBlock(b.beginLine, b.beginColumn);
                block.getStatements().addAll(stmts);
                {if (true) return block;}
    throw new Error("Missing return statement in function");
  }

  final public AstIf IfBlock() throws ParseException {
        Token b;
        AstExpression c;
        AstBlock trueBlock;
        Token el;
        AstBlock elseBlock = null;
        List<AstElif> elseIfs = new ArrayList<AstElif>();
        AstElif elif;
    b = jj_consume_token(IF);
    jj_consume_token(LPAREN);
    c = Expression();
    jj_consume_token(RPAREN);
    trueBlock = Block();
    label_8:
    while (true) {
      if (jj_2_22(2)) {
        ;
      } else {
        break label_8;
      }
      elif = ElseIfBlock();
                             elseIfs.add(elif);
    }
    if (jj_2_23(2)) {
      jj_consume_token(ELSE);
      elseBlock = Block();
    } else {
      ;
    }
                AstIf ifNode = new AstIf(b.beginLine, b.beginColumn);
                ifNode.setCondition(c);
                ifNode.setTrueBlock(trueBlock);
                ifNode.getElseIfs().addAll(elseIfs);
                ifNode.setElseBlock(elseBlock);
                {if (true) return ifNode;}
    throw new Error("Missing return statement in function");
  }

  final public AstElif ElseIfBlock() throws ParseException {
        Token b;
        AstExpression c;
        AstBlock block;
    b = jj_consume_token(ELIF);
    jj_consume_token(LPAREN);
    c = Expression();
    jj_consume_token(RPAREN);
    block = Block();
                AstElif elif = new AstElif(b.beginLine, b.beginColumn);
                elif.setCondition(c);
                elif.setBlock(block);
                {if (true) return elif;}
    throw new Error("Missing return statement in function");
  }

  final public AstWhile WhileBlock() throws ParseException {
        Token b;
        AstExpression c;
        AstBlock block;
    b = jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    c = Expression();
    jj_consume_token(RPAREN);
    block = Block();
                AstWhile whileNode = new AstWhile(b.beginLine, b.beginColumn);
                whileNode.setCondition(c);
                whileNode.setBlock(block);
                {if (true) return whileNode;}
    throw new Error("Missing return statement in function");
  }

  final public AstFor ForBlock() throws ParseException {
        Token t;
        List<AstVariableDeclaration> i;
        AstExpression e;
        List<AstStatement> b;
        AstBlock block;
    t = jj_consume_token(FOR);
    jj_consume_token(LPAREN);
    i = ForInitializer();
    jj_consume_token(SEMICOLON);
    e = Expression();
    jj_consume_token(SEMICOLON);
    b = ForBottom();
    jj_consume_token(RPAREN);
    block = Block();
                AstFor forNode = new AstFor(t.beginLine, t.beginColumn);
                forNode.getInitializers().addAll(i);
                forNode.setCondition(e);
                forNode.getBottom().addAll(b);
                forNode.setBlock(block);
                {if (true) return forNode;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstVariableDeclaration> ForInitializer() throws ParseException {
        AstVariableDeclaration var;
        List<AstVariableDeclaration> vars = new ArrayList<AstVariableDeclaration>();
    if (jj_2_25(2)) {
      var = VariableDeclaration();
                                    vars.add(var);
      label_9:
      while (true) {
        if (jj_2_24(2)) {
          ;
        } else {
          break label_9;
        }
        jj_consume_token(COMMA);
        var = VariableDeclaration();
                                                                                    vars.add(var);
      }
    } else {
      ;
    }
                {if (true) return vars;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstStatement> ForBottom() throws ParseException {
        AstExpression e;
        List<AstStatement> stmts = new ArrayList<AstStatement>();
    if (jj_2_27(2)) {
      e = AssignmentOrExpression();
                                     stmts.add(e);
      label_10:
      while (true) {
        if (jj_2_26(2)) {
          ;
        } else {
          break label_10;
        }
        jj_consume_token(COMMA);
        e = AssignmentOrExpression();
                                                                                     stmts.add(e);
      }
    } else {
      ;
    }
                {if (true) return stmts;}
    throw new Error("Missing return statement in function");
  }

  final public AstReturn Return() throws ParseException {
        Token t;
        AstExpression e=null;
    t = jj_consume_token(RETURN);
    if (jj_2_28(2)) {
      e = Expression();
    } else {
      ;
    }
                AstReturn ret = new AstReturn(t.beginLine, t.beginColumn);
                ret.setValue(e);
                {if (true) return ret;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression AssignmentOrExpression() throws ParseException {
        AstExpression lhs;
        AstExpression rhs = null;
    lhs = Expression();
    if (jj_2_29(2)) {
      jj_consume_token(ASSIGN);
      rhs = Expression();
    } else {
      ;
    }
                if(rhs != null) {
                        AstBinaryOp assign = new AstBinaryOp(lhs.getLine(), lhs.getCol());
                        assign.setLeftHandSide(lhs);
                        assign.setRightHandSide(rhs);
                        assign.setOperator("=");
                        {if (true) return assign;}
                } else {
                        {if (true) return lhs;}
                }
    throw new Error("Missing return statement in function");
  }

  final public AstExpression Expression() throws ParseException {
        AstExpression e;
    e = LogicalExpression();
                {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression LogicalExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = BitExpression();
    label_11:
    while (true) {
      if (jj_2_30(2)) {
        ;
      } else {
        break label_11;
      }
      if (jj_2_31(2)) {
        op = jj_consume_token(SC_OR);
      } else if (jj_2_32(2)) {
        op = jj_consume_token(SC_AND);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = BitExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression BitExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = EqualityExpression();
    label_12:
    while (true) {
      if (jj_2_33(2)) {
        ;
      } else {
        break label_12;
      }
      if (jj_2_34(2)) {
        op = jj_consume_token(BIT_AND);
      } else if (jj_2_35(2)) {
        op = jj_consume_token(BIT_OR);
      } else if (jj_2_36(2)) {
        op = jj_consume_token(XOR);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = EqualityExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression EqualityExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = RelationalExpression();
    label_13:
    while (true) {
      if (jj_2_37(2)) {
        ;
      } else {
        break label_13;
      }
      if (jj_2_38(2)) {
        op = jj_consume_token(EQ);
      } else if (jj_2_39(2)) {
        op = jj_consume_token(NE);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = RelationalExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression RelationalExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = ShiftExpression();
    label_14:
    while (true) {
      if (jj_2_40(2)) {
        ;
      } else {
        break label_14;
      }
      if (jj_2_41(2)) {
        op = jj_consume_token(LT);
      } else if (jj_2_42(2)) {
        op = jj_consume_token(86);
      } else if (jj_2_43(2)) {
        op = jj_consume_token(LE);
      } else if (jj_2_44(2)) {
        op = jj_consume_token(GE);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = ShiftExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression ShiftExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = AddExpression();
    label_15:
    while (true) {
      if (jj_2_45(2)) {
        ;
      } else {
        break label_15;
      }
      if (jj_2_46(2)) {
        op = jj_consume_token(LSHIFT);
      } else if (jj_2_47(2)) {
        op = jj_consume_token(RSHIFT);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = AddExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression AddExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = MultExpression();
    label_16:
    while (true) {
      if (jj_2_48(2)) {
        ;
      } else {
        break label_16;
      }
      if (jj_2_49(2)) {
        op = jj_consume_token(PLUS);
      } else if (jj_2_50(2)) {
        op = jj_consume_token(MINUS);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = MultExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression MultExpression() throws ParseException {
        AstExpression last;
        Token op;
        AstExpression e;
    last = UnaryExpression();
    label_17:
    while (true) {
      if (jj_2_51(2)) {
        ;
      } else {
        break label_17;
      }
      if (jj_2_52(2)) {
        op = jj_consume_token(STAR);
      } else if (jj_2_53(2)) {
        op = jj_consume_token(SLASH);
      } else if (jj_2_54(2)) {
        op = jj_consume_token(REM);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = UnaryExpression();
                        AstBinaryOp logical = new AstBinaryOp(op.beginLine, op.beginColumn);
                        logical.setLeftHandSide(last);
                        logical.setRightHandSide(e);
                        logical.setOperator(op.image);
                        last = logical;
    }
                {if (true) return last;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression UnaryExpression() throws ParseException {
        Token op;
        AstExpression e=null;
    if (jj_2_58(2)) {
      e = PostfixExpression();
    } else if (jj_2_59(2)) {
      if (jj_2_55(2)) {
        op = jj_consume_token(BANG);
      } else if (jj_2_56(2)) {
        op = jj_consume_token(PLUS);
      } else if (jj_2_57(2)) {
        op = jj_consume_token(MINUS);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = UnaryExpression();
                        AstUnaryOp unary = new AstUnaryOp(op.beginLine, op.beginColumn);
                        unary.setExpression(e);
                        unary.setOperator(op.image);
                        e = unary;
    } else if (jj_2_60(2)) {
      op = jj_consume_token(TYPEOF);
      jj_consume_token(LPAREN);
      e = UnaryExpression();
      jj_consume_token(RPAREN);
                        AstUnaryOp typeof = new AstUnaryOp(op.beginLine, op.beginColumn);
                        typeof.setExpression(e);
                        typeof.setOperator(op.image);
                        e = typeof;
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression PostfixExpression() throws ParseException {
        AstExpression e;
        AstExpression index;
        List<AstExpression> args;
        Token t;
    e = PrimaryExpression();
    label_18:
    while (true) {
      if (jj_2_61(2)) {
        ;
      } else {
        break label_18;
      }
                 index=null; args=null; t=null;
      if (jj_2_63(2)) {
        t = jj_consume_token(LBRACKET);
        index = Expression();
        jj_consume_token(RBRACKET);
      } else if (jj_2_64(2)) {
        t = jj_consume_token(LPAREN);
        if (jj_2_62(2)) {
          args = ArgumentExpressionList();
        } else {
          ;
        }
        jj_consume_token(RPAREN);
      } else if (jj_2_65(2)) {
        jj_consume_token(DOT);
        t = jj_consume_token(IDENTIFIER);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
                        if(index != null) {
                                AstArrayLookup lookup = new AstArrayLookup(t.beginLine, t.beginColumn);
                                lookup.setArray(e);
                                lookup.setIndex(index);
                                e = lookup;
                        } else if(args != null) {
                                AstCall call = new AstCall(t.beginLine, t.beginColumn);
                                call.setTarget(e);
                                call.getArguments().addAll(args);
                                e = call;
                        } else {
                                AstReference ref = new AstReference(t.beginLine, t.beginColumn);
                                ref.setName(t.image);
                                AstGetElement element = new AstGetElement(t.beginLine, t.beginColumn);
                                element.setTarget(e);
                                element.setElement(ref);
                                e = element;
                        }
    }
                {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public List<AstExpression> ArgumentExpressionList() throws ParseException {
        List<AstExpression> args = new ArrayList<AstExpression>();
        AstExpression e;
    e = Expression();
                        args.add(e);
    label_19:
    while (true) {
      if (jj_2_66(2)) {
        ;
      } else {
        break label_19;
      }
      jj_consume_token(COMMA);
      e = Expression();
                             args.add(e);
    }
                {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public AstExpression PrimaryExpression() throws ParseException {
        Token t=null;
        AstExpression e=null;
    if (jj_2_67(2)) {
      t = jj_consume_token(IDENTIFIER);
    } else if (jj_2_68(2)) {
      e = Constant();
    } else if (jj_2_69(2)) {
      jj_consume_token(LPAREN);
      e = Expression();
      jj_consume_token(RPAREN);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                if(t!=null) {
                        AstReference ref = new AstReference(t.beginLine, t.beginColumn);
                        ref.setName(t.image);
                        {if (true) return ref;}
                } else {
                        {if (true) return e;}
                }
    throw new Error("Missing return statement in function");
  }

  final public AstLiteral Constant() throws ParseException {
        Token t;
        AstLiteral.LiteralType type = null;
    if (jj_2_70(2)) {
      t = jj_consume_token(BOOLEAN_LITERAL);
                                     type=AstLiteral.LiteralType.Boolean;
    } else if (jj_2_71(2)) {
      t = jj_consume_token(INTEGER_LITERAL);
                                     type=AstLiteral.LiteralType.Integer;
    } else if (jj_2_72(2)) {
      t = jj_consume_token(FLOATING_POINT_LITERAL);
                                            type=AstLiteral.LiteralType.Float;
    } else if (jj_2_73(2)) {
      t = jj_consume_token(CHARACTER_LITERAL);
                                       type=AstLiteral.LiteralType.Character;
    } else if (jj_2_74(2)) {
      t = jj_consume_token(STRING_LITERAL);
                                    type=AstLiteral.LiteralType.String;
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                AstLiteral lit = new AstLiteral(t.beginLine, t.beginColumn);
                lit.setValue(t.image);
                lit.setLiteralType(type);
                {if (true) return lit;}
    throw new Error("Missing return statement in function");
  }

  final public AstType Type() throws ParseException {
        Token t;
    if (jj_2_75(2)) {
      t = jj_consume_token(BOOL);
    } else if (jj_2_76(2)) {
      t = jj_consume_token(U8);
    } else if (jj_2_77(2)) {
      t = jj_consume_token(U16);
    } else if (jj_2_78(2)) {
      t = jj_consume_token(U32);
    } else if (jj_2_79(2)) {
      t = jj_consume_token(U64);
    } else if (jj_2_80(2)) {
      t = jj_consume_token(I8);
    } else if (jj_2_81(2)) {
      t = jj_consume_token(I16);
    } else if (jj_2_82(2)) {
      t = jj_consume_token(I32);
    } else if (jj_2_83(2)) {
      t = jj_consume_token(I64);
    } else if (jj_2_84(2)) {
      t = jj_consume_token(F32);
    } else if (jj_2_85(2)) {
      t = jj_consume_token(F64);
    } else if (jj_2_86(2)) {
      t = jj_consume_token(IDENTIFIER);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                AstType type = new AstType(t.beginLine, t.beginColumn);
                type.setName(t.image);
                {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  private boolean jj_2_64(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_64(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(63, xla); }
  }

  private boolean jj_2_65(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_65(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(64, xla); }
  }

  private boolean jj_2_66(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_66(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(65, xla); }
  }

  private boolean jj_2_67(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_67(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(66, xla); }
  }

  private boolean jj_2_68(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_68(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(67, xla); }
  }

  private boolean jj_2_69(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_69(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(68, xla); }
  }

  private boolean jj_2_70(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_70(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(69, xla); }
  }

  private boolean jj_2_71(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_71(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(70, xla); }
  }

  private boolean jj_2_72(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_72(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(71, xla); }
  }

  private boolean jj_2_73(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_73(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(72, xla); }
  }

  private boolean jj_2_74(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_74(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(73, xla); }
  }

  private boolean jj_2_75(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_75(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(74, xla); }
  }

  private boolean jj_2_76(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_76(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(75, xla); }
  }

  private boolean jj_2_77(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_77(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(76, xla); }
  }

  private boolean jj_2_78(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_78(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(77, xla); }
  }

  private boolean jj_2_79(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_79(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(78, xla); }
  }

  private boolean jj_2_80(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_80(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(79, xla); }
  }

  private boolean jj_2_81(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_81(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(80, xla); }
  }

  private boolean jj_2_82(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_82(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(81, xla); }
  }

  private boolean jj_2_83(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_83(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(82, xla); }
  }

  private boolean jj_2_84(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_84(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(83, xla); }
  }

  private boolean jj_2_85(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_85(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(84, xla); }
  }

  private boolean jj_2_86(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_86(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(85, xla); }
  }

  private boolean jj_3_49() {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_49()) {
    jj_scanpos = xsp;
    if (jj_3_50()) return true;
    }
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_42()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_51()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(VAR)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(DEF)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_83() {
    if (jj_scan_token(I64)) return true;
    return false;
  }

  private boolean jj_3_79() {
    if (jj_scan_token(U64)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(VAL)) return true;
    return false;
  }

  private boolean jj_3_47() {
    if (jj_scan_token(RSHIFT)) return true;
    return false;
  }

  private boolean jj_3_44() {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3_82() {
    if (jj_scan_token(I32)) return true;
    return false;
  }

  private boolean jj_3_78() {
    if (jj_scan_token(U32)) return true;
    return false;
  }

  private boolean jj_3_46() {
    if (jj_scan_token(LSHIFT)) return true;
    return false;
  }

  private boolean jj_3_43() {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_46()) {
    jj_scanpos = xsp;
    if (jj_3_47()) return true;
    }
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_41()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_48()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(STATIC)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_85() {
    if (jj_scan_token(F64)) return true;
    return false;
  }

  private boolean jj_3_81() {
    if (jj_scan_token(I16)) return true;
    return false;
  }

  private boolean jj_3_77() {
    if (jj_scan_token(U16)) return true;
    return false;
  }

  private boolean jj_3_42() {
    if (jj_scan_token(86)) return true;
    return false;
  }

  private boolean jj_3_86() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_84() {
    if (jj_scan_token(F32)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_80() {
    if (jj_scan_token(I8)) return true;
    return false;
  }

  private boolean jj_3_76() {
    if (jj_scan_token(U8)) return true;
    return false;
  }

  private boolean jj_3_75() {
    if (jj_scan_token(BOOL)) return true;
    return false;
  }

  private boolean jj_3_41() {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) return true;
    }
    }
    }
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(STRUCT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_39() {
    if (jj_scan_token(NE)) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_75()) {
    jj_scanpos = xsp;
    if (jj_3_76()) {
    jj_scanpos = xsp;
    if (jj_3_77()) {
    jj_scanpos = xsp;
    if (jj_3_78()) {
    jj_scanpos = xsp;
    if (jj_3_79()) {
    jj_scanpos = xsp;
    if (jj_3_80()) {
    jj_scanpos = xsp;
    if (jj_3_81()) {
    jj_scanpos = xsp;
    if (jj_3_82()) {
    jj_scanpos = xsp;
    if (jj_3_83()) {
    jj_scanpos = xsp;
    if (jj_3_84()) {
    jj_scanpos = xsp;
    if (jj_3_85()) {
    jj_scanpos = xsp;
    if (jj_3_86()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_74() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_73() {
    if (jj_scan_token(CHARACTER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_38() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3_72() {
    if (jj_scan_token(FLOATING_POINT_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3_39()) return true;
    }
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(ELIF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_71() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_70() {
    if (jj_scan_token(BOOLEAN_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_scan_token(XOR)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_39()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_70()) {
    jj_scanpos = xsp;
    if (jj_3_71()) {
    jj_scanpos = xsp;
    if (jj_3_72()) {
    jj_scanpos = xsp;
    if (jj_3_73()) {
    jj_scanpos = xsp;
    if (jj_3_74()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_35() {
    if (jj_scan_token(BIT_OR)) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_34() {
    if (jj_scan_token(BIT_AND)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(IMPORT)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3_35()) {
    jj_scanpos = xsp;
    if (jj_3_36()) return true;
    }
    }
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_69() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3_68() {
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3_67() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_37()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_67()) {
    jj_scanpos = xsp;
    if (jj_3_68()) {
    jj_scanpos = xsp;
    if (jj_3_69()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(SC_AND)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_47()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3_66() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_35()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_66()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) return true;
    }
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(SC_OR)) return true;
    return false;
  }

  private boolean jj_3_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) return true;
    }
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_62() {
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_65() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_64() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_62()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_63() {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_63()) {
    jj_scanpos = xsp;
    if (jj_3_64()) {
    jj_scanpos = xsp;
    if (jj_3_65()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_14()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_48()) return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_61()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_57() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3_54() {
    if (jj_scan_token(REM)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_56() {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3_60() {
    if (jj_scan_token(TYPEOF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_53() {
    if (jj_scan_token(SLASH)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_35()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_29()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3_55() {
    if (jj_scan_token(BANG)) return true;
    return false;
  }

  private boolean jj_3_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_55()) {
    jj_scanpos = xsp;
    if (jj_3_56()) {
    jj_scanpos = xsp;
    if (jj_3_57()) return true;
    }
    }
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3_58() {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  private boolean jj_3_52() {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  private boolean jj_3_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_52()) {
    jj_scanpos = xsp;
    if (jj_3_53()) {
    jj_scanpos = xsp;
    if (jj_3_54()) return true;
    }
    }
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_58()) {
    jj_scanpos = xsp;
    if (jj_3_59()) {
    jj_scanpos = xsp;
    if (jj_3_60()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_28()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_50() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_3R_28()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_26()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[86];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[87];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 87; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 86; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
            case 63: jj_3_64(); break;
            case 64: jj_3_65(); break;
            case 65: jj_3_66(); break;
            case 66: jj_3_67(); break;
            case 67: jj_3_68(); break;
            case 68: jj_3_69(); break;
            case 69: jj_3_70(); break;
            case 70: jj_3_71(); break;
            case 71: jj_3_72(); break;
            case 72: jj_3_73(); break;
            case 73: jj_3_74(); break;
            case 74: jj_3_75(); break;
            case 75: jj_3_76(); break;
            case 76: jj_3_77(); break;
            case 77: jj_3_78(); break;
            case 78: jj_3_79(); break;
            case 79: jj_3_80(); break;
            case 80: jj_3_81(); break;
            case 81: jj_3_82(); break;
            case 82: jj_3_83(); break;
            case 83: jj_3_84(); break;
            case 84: jj_3_85(); break;
            case 85: jj_3_86(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
