/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.badlogicgames.quack.parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int IMPORT = 12;
  /** RegularExpression Id. */
  int MODULE = 13;
  /** RegularExpression Id. */
  int DEF = 14;
  /** RegularExpression Id. */
  int STATIC = 15;
  /** RegularExpression Id. */
  int VAL = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int STRUCT = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELIF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int SIZEOF = 26;
  /** RegularExpression Id. */
  int TYPEOF = 27;
  /** RegularExpression Id. */
  int CAST = 28;
  /** RegularExpression Id. */
  int BOOL = 29;
  /** RegularExpression Id. */
  int U8 = 30;
  /** RegularExpression Id. */
  int U16 = 31;
  /** RegularExpression Id. */
  int U32 = 32;
  /** RegularExpression Id. */
  int U64 = 33;
  /** RegularExpression Id. */
  int I8 = 34;
  /** RegularExpression Id. */
  int I16 = 35;
  /** RegularExpression Id. */
  int I32 = 36;
  /** RegularExpression Id. */
  int I64 = 37;
  /** RegularExpression Id. */
  int F32 = 38;
  /** RegularExpression Id. */
  int F64 = 39;
  /** RegularExpression Id. */
  int ANY = 40;
  /** RegularExpression Id. */
  int ANYREF = 41;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 42;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 43;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 44;
  /** RegularExpression Id. */
  int HEX_LITERAL = 45;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 46;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 47;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 48;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 49;
  /** RegularExpression Id. */
  int STRING_LITERAL = 50;
  /** RegularExpression Id. */
  int IDENTIFIER = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int PART_LETTER = 53;
  /** RegularExpression Id. */
  int LPAREN = 54;
  /** RegularExpression Id. */
  int RPAREN = 55;
  /** RegularExpression Id. */
  int LBRACE = 56;
  /** RegularExpression Id. */
  int RBRACE = 57;
  /** RegularExpression Id. */
  int LBRACKET = 58;
  /** RegularExpression Id. */
  int RBRACKET = 59;
  /** RegularExpression Id. */
  int SEMICOLON = 60;
  /** RegularExpression Id. */
  int COMMA = 61;
  /** RegularExpression Id. */
  int DOT = 62;
  /** RegularExpression Id. */
  int AT = 63;
  /** RegularExpression Id. */
  int ASSIGN = 64;
  /** RegularExpression Id. */
  int LT = 65;
  /** RegularExpression Id. */
  int BANG = 66;
  /** RegularExpression Id. */
  int TILDE = 67;
  /** RegularExpression Id. */
  int HOOK = 68;
  /** RegularExpression Id. */
  int COLON = 69;
  /** RegularExpression Id. */
  int EQ = 70;
  /** RegularExpression Id. */
  int LE = 71;
  /** RegularExpression Id. */
  int GE = 72;
  /** RegularExpression Id. */
  int NE = 73;
  /** RegularExpression Id. */
  int SC_OR = 74;
  /** RegularExpression Id. */
  int SC_AND = 75;
  /** RegularExpression Id. */
  int INCR = 76;
  /** RegularExpression Id. */
  int DECR = 77;
  /** RegularExpression Id. */
  int PLUS = 78;
  /** RegularExpression Id. */
  int MINUS = 79;
  /** RegularExpression Id. */
  int STAR = 80;
  /** RegularExpression Id. */
  int SLASH = 81;
  /** RegularExpression Id. */
  int BIT_AND = 82;
  /** RegularExpression Id. */
  int BIT_OR = 83;
  /** RegularExpression Id. */
  int XOR = 84;
  /** RegularExpression Id. */
  int REM = 85;
  /** RegularExpression Id. */
  int LSHIFT = 86;
  /** RegularExpression Id. */
  int RSHIFT = 87;
  /** RegularExpression Id. */
  int ELLIPSIS = 88;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"import\"",
    "\"module\"",
    "\"def\"",
    "\"static\"",
    "\"val\"",
    "\"var\"",
    "\"struct\"",
    "\"if\"",
    "\"elif\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"sizeof\"",
    "\"typeof\"",
    "\"cast\"",
    "\"bool\"",
    "\"u8\"",
    "\"u16\"",
    "\"u32\"",
    "\"u64\"",
    "\"i8\"",
    "\"i16\"",
    "\"i32\"",
    "\"i64\"",
    "\"f32\"",
    "\"f64\"",
    "\"any\"",
    "\"anyref\"",
    "<BOOLEAN_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"...\"",
    "\">\"",
  };

}
